- name: Install GnuGP
  become: true
  ansible.builtin.package:
    state: present
    name: gnupg

- name: Ensure GnuPG directory exists
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    recurse: true
    state: directory

- name: "Copy GnuPG Files"
  ansible.builtin.copy:
    src: "{{ role_path}}/files/"
    dest: "{{ ansible_env.HOME }}/.gnupg"
    mode: 0600

- name: Import GPG Keys
  shell: |
    gpg --import secret_keys.asc
    gpg --import pub_keys.asc
    gpg --import-ownertrust otrust.txt

  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/.gnupg"
