- name: Ensure AWS directory exists
  file:
    path: "{{ ansible_env.HOME }}/.aws"
    recurse: true
    state: directory

- name: "Copy AWS Credentials"
  ansible.builtin.copy:
    src: "{{ role_path}}/files/credentials"
    dest: "{{ ansible_env.HOME }}/.aws/credentials"
    mode: 0600

- name: "Copy AWS Config"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_env.HOME }}/.aws/config"
    mode: 0600
