- name: "Install neovim"
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
    creates: /opt/nvim-linux64
    dest: /opt/
    remote_src: yes

- name: "Link neovim executable"
  ansible.builtin.file:
    src: "/opt/nvim-linux64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
    become: true
    force: true

- name: "Link neovim configuration"
  ansible.builtin.file:
    src: "nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
